// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * StartProxy
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @returns {Promise<string|Error>}  - Go Type: string
       */
      "StartProxy": (arg1, arg2, arg3) => {
        return window.go.main.App.StartProxy(arg1, arg2, arg3);
      },
    },
  },

};
export default go;
